### ISSUE TITLE
[FEATURE REQUEST] Discovey Center data

### ISSUE THREAD

**Issue by mauriciolauffer** [SAP-samples/btp-service-metadata#11]
### Area of the resources that should be enhanced?

Metadata of services

### Description

It'd be great to have the metadata aligned with the information available in [SAP Discovery Center](https://discovery-center.cloud.sap/serviceCatalog?regions=all&provider=all).

I've used the [OData Service](https://discovery-center.cloud.sap/servicecatalog/ServiceDetailss) behind SAP Discovery Center, and properties such as `Tags` and `LicenseModelType` are helpful.

### Link to resource

https://discovery-center.cloud.sap/servicecatalog/ServiceDetailss

**Comment by rui1610** [comment]
Hi Mauricio, we are already using the data that is used by Discovery Center. That's the reason, why you get as well links to the Discovery Center pages for a service as metadata.

As described in the [README](https://github.com/SAP-samples/btp-service-metadata/blob/main/README.md) we want to deliver the data in a way that is focusing on a specific persona. What I could think of is to define a new persona that is focusing on commercially focused data.

Would that make sense to you, too?

**Comment by lechnerc77** [comment]
No feedback received for 1 year - closing the issue
