### ISSUE TITLE
[BUG] Most of the mobile icons are missing

### ISSUE THREAD

**Issue by mauriciolauffer** [SAP-samples/btp-service-metadata#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which area of the resources should be corrected?

Service metadata

### Bug description

Mobile services don't have a proper icon, it's either `null` or a `ui5-icon` path which doesn't mean anything out of the ui5 framework.

`mobile-services` and `mobile-services-preview` are the only ones with a proper icon defined.

![image](https://user-images.githubusercontent.com/443888/202109019-9284e42b-8b21-40c9-9663-21e1af6269b9.png)

**Comment by rui1610** [comment]
Hi Mauricio, 
we agree with your statement. Unfortunately, there is no easy way to derive the correct icon for the services you've mentioned above. Therefore, we have removed them from the output with the last commit into this repo.

Once we can get the icon information for the services, you'll see them properly provided in the repo.
Thanks for raising the issue.

Best,
Rui
